# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-10-26 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_name', models.CharField(max_length=20)),
                ('park_count', models.IntegerField()),
                ('park_register', models.DateTimeField()),
                ('park_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
            options={
                'db_table': 'parks',
            },
        ),
    ]
